const { Router } = require('express');
const Controller = require('../controllers/productController');
const authentication = require('../middleware/authentication');
const authorization = require('../middleware/authorization');
const productRouter = Router();
productRouter.get('/', Controller.showProducts);
productRouter.get('/cart', authentication, Controller.showCart);
productRouter.post('/cart', authentication, Controller.addProductToCart);
productRouter.delete('/cart', authentication, Controller.emptyCart);
productRouter.put('/cart/:id', authentication, authorization, Controller.updateProductInCart);
productRouter.delete('/cart/:id', authentication, authorization, Controller.removeProductFromCart);
productRouter.post('/checkout',authentication, Controller.checkout);
module.exports = productRouter;